// Task 1 Updated/frontend/src/components/RemarksBlock.jsx
import { parseRemarks } from '../utils/helpers'

const SECTION_ORDER = ['FINDINGS', 'RISK ASSESSMENT', 'IMMEDIATE ACTIONS', 'LIFESTYLE MODIFICATIONS', 'RECOMMENDATION']

export default function RemarksBlock({ patientName, aiStatus, remarks, isFallback }) {
  const firstName = (patientName || '').trim().split(/\s+/)[0] || 'there'

  if (aiStatus === 'processing') {
    return (
      <div className="ai-loading">
        <div className="ai-loading-pulse">
          <span /><span /><span />
        </div>
        <p className="ai-loading-text">Analysing blood test results…</p>
        <p className="ai-loading-sub">This usually takes a few seconds.</p>
      </div>
    )
  }

  if (!remarks) {
    return <p style={{ color: 'var(--text-muted)' }}>No remarks available.</p>
  }

  const sections = parseRemarks(remarks)

  return (
    <div>
      {/* Greeting is generated by the application itself, never by the AI. */}
      <p className="remarks-greeting">Hi{" " + firstName || ""}, here's a summary of your blood test results.</p>
      {isFallback && (
        <div className="alert alert-warning mb-2">
          ⚠ Automated AI analysis was unavailable for this application — the remark below was
          generated automatically from simple reference-range comparison only.
        </div>
      )}
      {sections ? (
        <div className="remarks-sections">
          {SECTION_ORDER.filter(h => sections[h]).map(h => (
            <div className="remarks-section" key={h}>
              <h4>{h}</h4>
              <p>{sections[h]}</p>
            </div>
          ))}
        </div>
      ) : (
        <p style={{ whiteSpace: 'pre-wrap' }}>{remarks}</p>
      )}
    </div>
  )
}
